### ISSUE TITLE
Suggestion: Chamge title color

### ISSUE THREAD

**Issue by lumuella** [MFB3000/github-crash-course#1]
I think it looks better if the main title is a bit mor orange.

The styling rule could be change like this.

```css
h1 {
  color: #e8d4b2;
}
```
